### ISSUE TITLE
compilation error ...

### ISSUE THREAD

**Issue by kaka77** [STMSolutions/RmiTaste#1]
[ERROR] /home/test/tools/RmiTaste/src/main/java/m0/rmitaste/rmi/RmiRegistry.java:[4,24] error: cannot find symbol
  symbol:   class RMIReplyDataParser
  location: package m0.rmitaste.utils
[INFO] 1 error

**Comment by kaka77** [comment]
Attempt to use compilation on windows and Linux systems failed    :(

**Comment by mzer0one** [comment]
Thank you for reporting, it should work now :)
